clc;clear all;close all;
Located = ['/Users/yvette/GoogleDrive/thesis/pic/legend/'];
windcolor=[1 0.2 0.8; 0.4 0.4 0.4;...
        1 0.6 0; 0 0.4 0.8;...
        1 0.2 0.2; 0.4 0.7 0.7;...
        0 0.8 0.4];
%%
plot(1,3,'Marker','o','MarkerSize',5,'Color',windcolor(1,:),...
    'MarkerFaceColor',windcolor(1,:)); hold on
plot(1,1,'Marker','o','MarkerSize',5,'Color',windcolor(2,:),...
    'MarkerFaceColor',windcolor(2,:)); hold on
plot(2,2,'Marker','o','MarkerSize',5,'Color',windcolor(3,:),...
    'MarkerFaceColor',windcolor(3,:)); hold on

plot(2,4,'Marker','o','MarkerSize',5,'Color',windcolor(4,:),...
    'MarkerFaceColor',windcolor(4,:)); hold on
plot(1,5,'Marker','o','MarkerSize',5,'Color',windcolor(5,:),...
    'MarkerFaceColor',windcolor(5,:)); hold on
%plot(2,6,'Marker','o','MarkerSize',5,'Color',windcolor(6,:),...
%    'MarkerFaceColor',windcolor(6,:));
%plot(2,7,'Marker','o','MarkerSize',5,'Color',windcolor(6,:),...
%    'MarkerFaceColor',windcolor(7,:));
hold on

set(gcf,'Paperunits','centimeters','PaperPosition',[0 0 14 10]);
set(gca,'FontSize',12);
hl=legend('\rho_n=0.76','\rho_n=0.8','\rho_n=0.84','\rho_n=0.9','\rho_n=1',...
    'Location','bestoutside');%'Orientation','Horizontal');
set(hl,'Box','off');
print(gcf,'-depsc','-tiff', '-r100', [Located 'LG_ACompare1.eps']);

