clc;clear all;close all;
ExpName='dimer_exp10';
File=['J:/Granule/' ExpName '/ref/'];
load([File '110/exp_parameter1.mat']);

Particle='dimer';
ExpNumber=10;
ExpDate=[20140714];
ParNum=[80:10:120];
iwind='contiunous';
PicWidth=340;
PicHeight=340;

Exp_info=struct('particle',Particle,...
                'Number',ExpNumber,...
                'Date',ExpDate,...
                'Pnumber',ParNum,...
                'wind',iwind,...
                'width',PicWidth,...
                'height',PicHeight,...
                'ParColor',3,...
                'roi',roi,...
                'BCenter',[ox oy],...
                'BRadius',R,...
                'scale',scale...
                );
save([File '/exp_parameter.mat'],'Exp_info');


